# dl_jobs: config
# cpu_image: us.gcr.io/dl-ci-cd/images/tasks/public/py3.7/default:v2019.11.18-6-ga7ee1224
cpu_image: us.gcr.io/dl-ci-cd/images/tasks/public/py3.6/default:v2019.11.18-6-ga7ee1224
gpu_image: us.gcr.io/dl-ci-cd/images/tasks/public/py3.6-gpu/default:v2019.11.18-6-ga7ee1224
cpu_job: true
cpus: 1
default_method: task
dls_root: dl_jobs
errors_dir: data/errors
gpus: 0
is_dev: true
log: true
log_dir: data/logs
module_dir: run
noisy: true
print_logs: true
results_dir: data/results
save_errors: true
save_results: true
suppress:
- DeprecationWarning
- FutureWarning